version: "3"
services:
  tests:
    image: mbta-app
    build: .
    environment:
      - PYTHONUNBUFFERED=true
      - PYTHONPATH=.
    command: "pytest --cov=mbta_back_end tests"
    stdin_open: true
    tty: true
  web:
    image: mbta-app
    build: .
    environment:
      - PYTHONUNBUFFERED=true
    command:
      [
        "uvicorn",
        "mbta_back_end:app",
        "--log-level",
        "debug",
        "--reload",
        "--reload-dir",
        "mbta_back_end/",
        "--host",
        "0.0.0.0",
      ]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
